# Configura a URL base do servidor ollama.
quarkus.langchain4j.ollama.base-url=http://localhost:11434/

# Define o ID do modelo que o Langchain4j irá invocar no Ollama
quarkus.langchain4j.ollama.chat-model.model-id=gpt-oss:20b

# Define um timeout para a chamada
# Se o modelo demorar mais de 60s para responder, a chamada falhará.
quarkus.langchain4j.ollama.timeout=1500s

#quarkus.langchain4j.easy-rag.path=src/main/resources/rag
#quarkus.langchain4j.easy-rag.max-segment-size=100
## usa 20% do segment size
#quarkus.langchain4j.easy-rag.max-over lap-size=20

## config embedding model
quarkus.langchain4j.ollama.embedding-model.model-id=nomic-embed-text

## config do pgVector
quarkus.langchain4j.pgvector.register-vector-pg-extension=true

## o nomic tem 768 dimensões isso é fixo por embedding
quarkus.langchain4j.pgvector.dimension=768
quarkus.langchain4j.pgvector.table=travel_embeddings
quarkus.langchain4j.pgvector.drop-table-first=false

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres

# -- Configuração de Loggin do langChain4j
# Loga a requisição completa enviada para o LLM (incluindo o manifesto de Tools)
quarkus.langchain4j.log-requests=true

# Loga a resposta completa recebida do LLM (incluindo a chamada de tool)
quarkus.langchain4j.log-responses=true

quarkus.langchain4j.mcp.booking-server.transport-type=streamable-http
quarkus.langchain4j.mcp.booking-server.url=http://localhost:8081/mcp

quarkus.langchain4j.mcp.booking-server.timeout=3000s